[package]
name = "hamrah-api"
version = "0.1.0"
edition = "2021"
authors = ["Mike Hamrah <m@hamrah.com>"]

[package.metadata.release]
release = false

[lib]
crate-type = ["cdylib"]

[dependencies]
worker = { version = "0.6", features = ['http', 'axum', 'd1'] }
worker-macros = { version = "0.6", features = ['http'] }
axum = { version = "0.8", default-features = false, features = [
    "json",
    "tokio",
    "http1",
    "query",
    "matched-path",
] }
tower-service = "0.3.3"
console_error_panic_hook = { version = "0.1.7" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = { version = "1.0", features = ["v4", "serde"] }
chrono = { version = "0.4", features = ["serde"] }
sha2 = "0.10"
base32 = "0.5"
hex = "0.4"
rand = "0.8"
tower = "0.5"
tower-http = { version = "0.6", features = ["cors"] }
thiserror = "1.0"
sqlx = { version = "0.8", features = [
    "runtime-tokio-rustls",
    "chrono",
    "uuid",
] }
webauthn-rs = { version = "0.5", features = [
    "danger-allow-state-serialisation",
] }
sqlx-d1 = { version = "0.2.0" }
base64 = "0.22"
