name = "hamrah-api"
main = "build/worker/shim.mjs"
compatibility_date = "2025-08-22"
compatibility_flags = ["nodejs_compat"]

[build]
command = "cargo install -q worker-build && worker-build --release"

[[d1_databases]]
binding = "DB"
database_name = "prod-hamrah-app-auth"
database_id = "aa57b2da-516e-4f48-8595-52ecc887787a"

[vars]
APPLE_TEAM_ID = "UR6RM9YCF7"
APPLE_BUNDLE_ID = "app.hamrah.ios"
ENVIRONMENT = "production"
APPLE_KEY_ID = "PGW4JA9UQF"

[[rules]]
globs = ["**/*.wasm"]
type = "CompiledWasm"
fallthrough = false

[observability.logs]
enabled = true
