name = "hamrah-api"
main = "build/worker/shim.mjs"
compatibility_date = "2025-08-22"

[[routes]]
pattern = "api.hamrah.app/*"

[build]
command = "cargo install -q worker-build && worker-build --release"