name = "hamrah-api"
main = "build/worker/shim.mjs"
# Cloudflare Workers compatibility_date is pinned to the latest known, tested date.
# Bump periodically to adopt new features/bug fixes after verifying in preview.
# Keep this in sync with:
# - workers/api/wrangler.preview.toml
# - workers/link-pipeline/wrangler.toml
# - workers/link-pipeline/vitest.config.ts (compatibilityDate)
compatibility_date = "2025-09-15"
compatibility_flags = ["nodejs_compat"]

[build]
command = "worker-build --release"

[[d1_databases]]
binding = "DB"
database_name = "prod-hamrah-app-auth"
database_id = "aa57b2da-516e-4f48-8595-52ecc887787a"

[ai]
binding = "AI"

[[r2_buckets]]
binding = "ARCHIVES"
bucket_name = "hamrah-archives"



[[services]]
binding = "PIPELINE_SERVICE"
service = "hamrah-link-pipeline"

[vars]
APPLE_TEAM_ID = "UR6RM9YCF7"
APPLE_BUNDLE_ID = "app.hamrah.ios"
ENVIRONMENT = "production"
APPLE_KEY_ID = "PGW4JA9UQF"

[[rules]]
globs = ["**/*.wasm"]
type = "CompiledWasm"
fallthrough = false

[observability.logs]
enabled = true
