name = "hamrah-api-preview"
# CI note: For per-PR previews, the deploy workflow overrides the Worker name:
# - hamrah-api-pr-<PR_NUMBER> (for pull_request runs)
# - hamrah-api-manual-<RUN_NUMBER> (for manual workflow_dispatch runs)
# See .github/workflows/deploy.yml for the dynamic naming logic.
main = "build/worker/shim.mjs"
# Cloudflare Workers compatibility_date is pinned to the latest known, tested date.
# Bump periodically to adopt new features/bug fixes after verifying in preview.
# Keep this in sync with:
# - workers/api/wrangler.toml
# - workers/link-pipeline/wrangler.toml
# - workers/link-pipeline/vitest.config.ts (compatibilityDate)
compatibility_date = "2025-07-18"
compatibility_flags = ["nodejs_compat"]

[build]
command = "worker-build --release"

[[d1_databases]]
binding = "DB"
database_name = "prod-hamrah-app-auth"  # Use prod database for previews (safe for preview deployments)
database_id = "aa57b2da-516e-4f48-8595-52ecc887787a"

[ai]
binding = "AI"





[[services]]
binding = "PIPELINE_SERVICE"
service = "hamrah-link-pipeline-preview"
# CI note: For per-PR previews, this binding is rewritten at deploy-time to the matching
# per-PR pipeline worker:
# - hamrah-link-pipeline-pr-<PR_NUMBER> (for pull_request runs)
# - hamrah-link-pipeline-manual-<RUN_NUMBER> (for manual workflow_dispatch runs)

[vars]
APPLE_TEAM_ID = "UR6RM9YCF7"
APPLE_BUNDLE_ID = "app.hamrah.ios"
ENVIRONMENT = "preview"
APPLE_KEY_ID = "PGW4JA9UQF"

[[rules]]
globs = ["**/*.wasm"]
type = "CompiledWasm"
fallthrough = false

[observability.logs]
enabled = true
