#:schema node_modules/wrangler/config-schema.json
name = "hamrah-link-pipeline"
main = "dist/index.js"
compatibility_date = "2025-09-15"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"

# Workers AI binding (available in code as env.AI)
[ai]
binding = "AI"

# D1 database used by the workflow for pipeline state and application data
[[d1_databases]]
binding = "DB"
database_name = "prod-hamrah-app-auth"
database_id = "aa57b2da-516e-4f48-8595-52ecc887787a"



# Workflow entrypoint binding
# Other Workers can call this workflow by creating an instance via env.LINK_PIPELINE
[[workflows]]
name = "link-pipeline"
binding = "LINK_PIPELINE"
class_name = "LinkPipelineWorkflow"

[observability.logs]
enabled = true

# Preview environment configuration
[env.preview]
name = "hamrah-link-pipeline-preview"

[env.preview.ai]
binding = "AI"

[[env.preview.d1_databases]]
binding = "DB"
database_name = "prod-hamrah-app-auth"  # Use same database for preview
database_id = "aa57b2da-516e-4f48-8595-52ecc887787a"



[[env.preview.workflows]]
name = "link-pipeline-preview"
binding = "LINK_PIPELINE"
class_name = "LinkPipelineWorkflow"

[env.preview.observability.logs]
enabled = true
