name: Cleanup Preview Workers

on:
  pull_request:
    types: [closed]
  workflow_dispatch:
    inputs:
      pr_number:
        description: "PR number to clean up (e.g., 123). If provided, preview_id is ignored."
        required: false
        type: string
      preview_id:
        description: "Explicit preview identifier (e.g., pr-123 or manual-456). Used when pr_number is not provided."
        required: false
        type: string

permissions:
  contents: read

jobs:
  cleanup:
    name: Delete per-PR preview Workers
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Determine preview identifiers
        shell: bash
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            echo "PREVIEW_ID=pr-${{ github.event.pull_request.number }}" >> $GITHUB_ENV
          else
            if [ -n "${{ inputs.pr_number }}" ]; then
              echo "PREVIEW_ID=pr-${{ inputs.pr_number }}" >> $GITHUB_ENV
            elif [ -n "${{ inputs.preview_id }}" ]; then
              echo "PREVIEW_ID=${{ inputs.preview_id }}" >> $GITHUB_ENV
            else
              echo "SKIP_CLEANUP=1" >> $GITHUB_ENV
              echo "No pr_number or preview_id provided for manual run; skipping cleanup."
            fi
          fi

          if [ -z "${SKIP_CLEANUP}" ]; then
            echo "API_WORKER_NAME=hamrah-api-${PREVIEW_ID}" >> $GITHUB_ENV
            echo "PIPELINE_WORKER_NAME=hamrah-link-pipeline-${PREVIEW_ID}" >> $GITHUB_ENV
          fi

      - name: Show computed names
        if: env.SKIP_CLEANUP != '1'
        run: |
          echo "Preview ID: $PREVIEW_ID"
          echo "API Worker: $API_WORKER_NAME"
          echo "Pipeline Worker: $PIPELINE_WORKER_NAME"

      - name: Delete API Preview Worker
        if: env.SKIP_CLEANUP != '1'
        uses: cloudflare/wrangler-action@v3
        continue-on-error: true
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: delete --name ${{ env.API_WORKER_NAME }}
          workingDirectory: workers/api

      - name: Delete Pipeline Preview Worker
        if: env.SKIP_CLEANUP != '1'
        uses: cloudflare/wrangler-action@v3
        continue-on-error: true
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: delete --name ${{ env.PIPELINE_WORKER_NAME }}
          workingDirectory: workers/link-pipeline
